# Provided by HBO-ICT
# Source https://docs.portainer.io/advanced/reverse-proxy/traefik

version: "3.7"

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    command:
      # https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - --entrypoints.websecure.address=:443
      - --providers.docker
      - --log.level=DEBUG
      # - --certificatesresolvers.leresolver.acme.httpchallenge=true
      # - --certificatesresolvers.leresolver.acme.email=your-email #Set your email address here, is for the generation of SSL certificates with Let's Encrypt. 
      # - --certificatesresolvers.leresolver.acme.storage=./acme.json
      # - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web

    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      # - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data # Note where this directory is being created and check .gitignore and .dockerignore
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      # - "traefik.http.routers.frontend.tls.certresolver=leresolver"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.localhost`)"
      - "traefik.http.routers.edge.entrypoints=web"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      # - "traefik.http.routers.edge.tls.certresolver=leresolver"


# volumes:
#   portainer_data: